import SubMenuNavLink from '@/components/submenu-navlink'
import { Separator } from '@/components/ui/separator'
import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Purchase',
    //   description:
    //     'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="grid flex-1 grid-cols-[200px_5px_1fr]">
            <div className="flex flex-col items-center text-center">
                <Separator />
                <SubMenuNavLink
                    href="/purchase/purchase-order"
                    label="ใบสั่งซื้อ"
                />
                <Separator />
                <SubMenuNavLink
                    href="/purchase/purchase-received"
                    label="รับสินค้า"
                />
                <Separator />
                <SubMenuNavLink href="/purchase/payment" label="ใบสำคัญจ่าย" />
                <Separator />
            </div>
            <Separator orientation="vertical" className="h-full" />
            <div className="mb-2 p-3">{children}</div>
        </div>
    )
}
