import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import LogoutButton from '../components/LogoutButton'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  async function logout() {
    'use server'
    cookies().delete('token')
    redirect('/auth/login')
  }
  return (
    <>
      <div className='w-screen h-screen grid grid-cols-[200px_1fr]'>
        <div className='w-full h-full border-b flex flex-col p-3 border-r-2 border-slate-300 bg-slate-200 justify-between'>
          <Image
            src={'/BestPart_AI.jpg'}
            alt={'BestPartLogo'}
            height={300}
            width={300}
            className='rounded-full'
          />
          <form action={logout}>
            <button className=''>Logout</button>
          </form>
        </div>
        <main className='p-3'>{children}</main>
      </div>
    </>
  )
}
