import type { Metadata } from 'next'
import { Inter as FontSans, Sarabun } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import LayoutComponent from '@/components/layout-component'
import { getServerSession } from 'next-auth'

import SessionProvider from '@/components/session-provider'
import { authOptions } from './api/auth/[...nextauth]/authOptions'
import LoginComponent from '@/components/login-component'
import { SpeedInsights } from '@vercel/speed-insights/next'
import CreateUser from './auth/create/page'

export const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const fontThai = Sarabun({
    subsets: ['thai', 'latin'],
    weight: '400',
    variable: '--font-thai',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getServerSession(authOptions)

    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    'min-h-screen bg-background font-sans antialiased',
                    fontThai.variable,
                    fontSans.variable
                )}
            >
                <SpeedInsights />
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <SessionProvider session={session}>
                        {session && (
                            <LayoutComponent>{children}</LayoutComponent>
                        )}
                        {!session && (
                            <main className="h-screen w-screen p-36">
                                <LoginComponent />
                            </main>
                        )}
                    </SessionProvider>

                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    )
}
