import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import {
  cookies,
  headers,
} from 'next/headers'
import {
  RedirectType,
  redirect,
} from 'next/navigation'
import { AuthPayloadSchema } from '../app/model/payload'
import { revalidatePath } from 'next/cache'
import Link from 'next/link'
import { Separator } from '@/components/ui/separator'
import { ModeToggle } from '@/components/mode-toggle'
import { NavMenu } from '@/components/nav-menu'
import { NavMenubar } from '@/components/nav-menubar'
import { Button } from '@/components/ui/button'
import UploadButton from '@/components/upload-button'
import { z } from 'zod'
import UserAvatar from './user-avatar'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description:
    'Generated by create next app',
}

export default async function LayoutComponent({
  children,
}: {
  children: React.ReactNode
}) {
  const userObject = JSON.parse(
    headers().get('user') as string
  )
  const userValidation =
    AuthPayloadSchema.safeParse(
      userObject
    )

  let user: z.infer<
    typeof AuthPayloadSchema
  >
  if (!userValidation.success)
    return <>{children}</>
  user = userValidation.data

  const upload = async (
    formData: FormData
  ) => {
    'use server'

    const file = formData.get('file')
    console.log(file)
  }

  return (
    <div className='min-h-screen flex flex-col'>
      <div className='w-screen h-14 flex items-center justify-between pr-5'>
        <a
          className='flex h-7 items-center justify-center rounded-full text-primary
        px-4 text-center text-sm transition-colors font-bold mr-5'>
          BestPart Alai
        </a>
        <nav className='flex space-x-6 flex-1'>
          {/* <NavMenu /> */}
          <NavMenubar />
        </nav>
        <div className='mr-2 flex items-center gap-2'>
          <ModeToggle />
          <UserAvatar user={user} />
        </div>
      </div>
      <Separator />

      {children}
    </div>
  )
}
