/**
 * Generated by AI
 * Calculate discounted price from a string of discounts.
 *
 * The string is space-separated list of discounts. Each discount is a number
 * optionally followed by a unit which is either '%' or 'B' (for baht). If the
 * unit is '%' then the discount is percentage of the price, otherwise it is a
 * fixed amount of money.
 *
 * The discounts are applied in sequence, i.e. the result of the previous
 * discount is used as the input for the next discount.
 *
 * Example: "10% 50B" means 10% discount followed by 50 baht discount.
 */
export function calculateDiscount(price: number, discountString?: string) {
    if (!discountString) return price

    const discountList = discountString?.split(' ') || []
    let result = price
    for (const discount of discountList) {
        const match = discount.match(/(\d+(\.\d+)?)([Bb%]?)$/i)
        if (match) {
            const value = parseFloat(match[1])
            switch (match[3].toUpperCase()) {
                case '':
                    result -= (result * value) / 100
                    break
                case '%':
                    result -= (result * value) / 100
                    break
                case 'B':
                    result -= value
                    break
            }
        }
    }
    return result
}
