import SubMenuNavLink from '@/components/submenu-navlink'
import { Separator } from '@/components/ui/separator'
import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Inventory',
    //   description:
    //     'Generated by create next app',
}

export default async function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="grid flex-1 grid-cols-[200px_5px_1fr]">
            <div className="flex flex-col items-center text-center">
                <Separator />
                <SubMenuNavLink href="/inventory" label="Inventory" />
                <Separator />
                <SubMenuNavLink
                    href="/inventory/part-number"
                    label="Part Number"
                />
                <Separator />
            </div>
            <Separator orientation="vertical" className="h-full" />
            {children}
        </div>
    )
}
