import SubMenuNavLink from '@/components/submenu-navlink'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Metadata } from 'next'
import Link from 'next/link'
import { DateRangePicker } from '@/components/ui/date-range-picker'

export const metadata: Metadata = {
    title: 'รายการขาย',
    //   description:
    //     'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="grid flex-1 grid-cols-[200px_5px_1fr]">
            <div className="flex flex-col items-center text-center">
                <Separator />
                <SubMenuNavLink href="/sales/sales-order" label="บิลขาย" />
                <Separator />
                <SubMenuNavLink href="/sales/return" label="รับคืนสินค้า" />
                <Separator />
                <SubMenuNavLink href="/sales/bill" label="ใบวางบิล" />
                <Separator />
                <SubMenuNavLink href="/sales/quotation" label="ใบเสนอราคา" />
                <Separator />
                <SubMenuNavLink
                    href="/sales/customer-order"
                    label="ใบจองสินค้า"
                />
                <Separator />
            </div>
            <Separator orientation="vertical" className="h-full" />
            <div className="mb-2 p-3">{children}</div>
        </div>
    )
}
