import DateRangePickerSearchParams from '@/components/date-range-picker-search-params'
import SubMenuNavLink from '@/components/submenu-navlink'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'รายการปรับปรุง (JV)',
    //   description:
    //     'Generated by create next app',
}

export default async function JournalVoucherLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <h1 className="mb-2 flex items-center gap-2 text-3xl text-primary">
                <span>รายการปรับปรุง (JV)</span>
                <Link href={'/accounting/journal-voucher/create'}>
                    <Button className="ml-3" variant={'outline'}>
                        เพิ่ม JV
                    </Button>
                </Link>
            </h1>
            <DateRangePickerSearchParams />
            {children}
        </>
    )
}
