import SubMenuNavLink from '@/components/submenu-navlink'
import { Separator } from '@/components/ui/separator'
import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Accounting',
    //   description:
    //     'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="grid flex-1 grid-cols-[200px_5px_1fr]">
            <div className="flex flex-col items-center text-center">
                <Separator />
                <SubMenuNavLink href="/accounting" label="Chart of Account" />
                <Separator />
                <SubMenuNavLink
                    href="/accounting/balance-sheet"
                    label="Balance Sheet"
                />
                <Separator />
                <SubMenuNavLink href="/accounting/cash" label="Cash" />
                <Separator />
                <SubMenuNavLink
                    href="/accounting/asset-management"
                    label="Asset Management"
                />
                <Separator />
                <SubMenuNavLink
                    href="/accounting/other-invoice"
                    label="ค่าใช้จ่ายอื่น"
                />
                <Separator />
                <SubMenuNavLink href="/accounting/payment" label="Payment" />
                <Separator />
            </div>
            <Separator orientation="vertical" className="h-full" />
            <div className="mb-2 p-3">{children}</div>
        </div>
    )
}
